# Generated by Django 3.1.4 on 2021-01-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='date_monumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('height', models.PositiveIntegerField()),
                ('creation', models.PositiveIntegerField()),
            ],
        ),
    ]
